- server/app/templates/app/aroundMeFront.css
- server/app/templates/app/aroundMeFront.html
#17 Added website's front end view
> I added the homepage

- README.md
> Depuleio patch 1

- server/server/urls.py
> hopefuly fixed this

- server/app/templates/app/aroundMeFront.html
> fixed href

- templates/base.html
- templates/eventpage.html
> Added UI for categories, I guess its becuase Im Sada and Im the best lol

- boards/views.py
> fixed print error

- boards/admin.py
#43 Fixed import of Event in admin.py
> fixed import

- static/css/eventpage.css
- templates/base.html
- templates/eventpage.html
#47 
Changes in Create Event Form
> Add Event Changes

- myproject/settings.py
- templates/eventpage.html
> Made changes to event page and settings

- boards/forms.py
- boards/models.py
- boards/views.py
- myproject/settings.py
- templates/base.html
- templates/eventpage.html
> fixed merge

- boards/views.py
> made sufficient changes

- boards/views.py
- templates/eventpage.html
- templates/landing.html
Compare: Develop
Base: Master
#66
> Merge Develop into Master

- myproject/settings.py
#69 Debug mode for collaborators (to run on localhost)
> added debug mode

- boards/views.py
- myproject/urls.py
- static/css/app.css
- static/css/landing.css
- templates/base.html
- templates/landing.html
#79 Making necessary changes to accommodate Add On feature! Fixed few issues and layout with landing page and homepage from feedback that was provided.
> Made changes to landing Page, Home page and eventPage and event section

- boards/views.py
- myproject/settings.py
- templates/base.html
> This is our add on features

- templates/base.html
> fixed some stuff with base.html

- boards/views.py
- templates/base.html
- templates/eventpage.html
> added filtering

- static/css/eventform.css
- templates/eventpage.html
> Created event form page

- templates/eventform.html
> Adding an event form

- boards/models.py
- boards/views.py
- templates/eventform.html
- templates/eventpage.html
> got maps working

- templates/base.html
> we fixed it

- boards/models.py
- boards/views.py
- myproject/urls.py
- templates/eventform.html
> changes for demo

- accounts/forms.py
- accounts/views.py
- boards/models.py
- boards/views.py
- myproject/urls.py
- templates/base.html
- templates/eventform.html
- templates/eventpage.html
> official release
